/**
 * Build all examples and fixtures into aptos packages under out/aptos
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { compile } from '../dist/compiler.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const projectRoot = path.resolve(__dirname, '..');
const outRoot = path.join(projectRoot, 'out', 'aptos');
const examplesDir = path.join(projectRoot, 'examples');
const fixturesDir = path.join(projectRoot, 'tests', 'fixtures', 'input');

function slugify(name) {
  // Convert CamelCase to kebab-case, then lowercase
  return name
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[^a-z0-9-]/gi, '-')
    .replace(/-+/g, '-')
    .replace(/(^-|-$)/g, '')
    .toLowerCase();
}

function extractContractName(source) {
  // Try to extract contract name from contract keyword
  let match = source.match(/contract\s+([A-Za-z_][A-Za-z0-9_]*)/);
  if (match) return match[1];
  
  // Try to extract from module keyword (Move syntax)
  match = source.match(/module\s+(?:0x[0-9a-fA-F]+::)?([A-Za-z_][A-Za-z0-9_]*)/);
  if (match) return match[1];
  
  return null;
}

function makeMoveToml(pkgName, moduleName = null) {
  // Use Movement's aptos-core with elsa revision (compatible with devnet)
  // The [addresses] section allows overriding at publish time
  return `# Auto-generated Move.toml
# Generated by MoveJS Compiler
# Update [addresses] with your deployer address before publishing
[package]
name = "${pkgName}"
version = "0.1.0"
authors = ["Js2Move <dev@movementlabs.xyz>"]

[dependencies]
AptosFramework = { git = "https://github.com/movementlabsxyz/aptos-core.git", rev = "9dfc8e7a3d622597dfd81cc4ba480a5377f87a41", subdir = "aptos-move/framework/aptos-framework" }

[addresses]
${moduleName || 'Module'} = "0x0"
std = "0x1"
`;
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function writePackage(pkgName, moduleName, code) {
  const pkgDir = path.join(outRoot, pkgName);
  const sourcesDir = path.join(pkgDir, 'sources');
  ensureDir(sourcesDir);

  const toml = makeMoveToml(pkgName, moduleName);
  fs.writeFileSync(path.join(pkgDir, 'Move.toml'), toml, 'utf-8');

  const fileName = `${moduleName}.move`;
  fs.writeFileSync(path.join(sourcesDir, fileName), code, 'utf-8');
}

function buildFromFile(filePath, sourceType = 'examples') {
  const src = fs.readFileSync(filePath, 'utf-8');
  
  // Extract from filename first (more reliable)
  let contractName = path.basename(filePath)
    .replace(/^\d+-/, '') // Remove numbering like "01-"
    .replace(/\.[^.]+$/, ''); // Remove extension
  
  // Only fall back to code extraction if filename is generic
  if (contractName === 'index' || contractName === 'contract') {
    const extracted = extractContractName(src);
    if (extracted && extracted.length >= 2) {
      contractName = extracted;
    }
  }

  // Create descriptive package name with source context
  const baseSlug = slugify(contractName);
  const sourcePrefix = sourceType === 'fixtures' ? 'fixture' : 'example';
  const pkgName = `${sourcePrefix}-${baseSlug}`;
  const moduleName = contractName;

  try {
    const result = compile(src, { skipSemanticAnalysis: true, format: 'pretty', indentSize: 2 });
    let code = typeof result === 'string' ? result : result.code;

    // Wrap in address block for Aptos compilation
    code = `address 0x1 {\n${code}\n}`;

    writePackage(pkgName, moduleName, code);
    console.log(`✓ Wrote package: ${pkgName}\n  Module: ${moduleName}\n  Source: ${filePath}`);
    console.log(); // Add line gap for better readability
  } catch (err) {
    console.error(`❌ Compilation failed for ${filePath}:`);
    
    // Split error message into lines and process each
    const errorLines = err.message.split('\n');
    let hasShownContext = false;
    
    for (const line of errorLines) {
      console.error(`   ${line}`);
      
      // Try to extract line/column info - format: "line:column - message"
      const errorMatch = line.match(/^(\d+):(\d+)\s*-\s*(.+)$/);
      if (errorMatch && !hasShownContext) {
        const lineNum = parseInt(errorMatch[1]);
        const colNum = parseInt(errorMatch[2]);
        const errorMsg = errorMatch[3];
        
        console.error(`   Line ${lineNum}, Column ${colNum}: ${errorMsg}`);
        
        // Show the problematic line with context
        const lines = src.split('\n');
        if (lineNum <= lines.length) {
          const startLine = Math.max(1, lineNum - 2);
          const endLine = Math.min(lines.length, lineNum + 2);
          
          console.error(`   Code context:`);
          for (let i = startLine; i <= endLine; i++) {
            const marker = i === lineNum ? '>>>' : '   ';
            const lineContent = lines[i - 1] || '';
            console.error(`${marker} ${i.toString().padStart(3)}: ${lineContent}`);
            if (i === lineNum && colNum > 0) {
              // Show column pointer
              const pointer = ' '.repeat(marker.length + 4 + colNum - 1) + '^';
              console.error(pointer);
            }
          }
        }
        
        hasShownContext = true; // Only show context for first error
      }
    }
    
    console.error(); // Empty line for spacing
  }
}

function collectFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter(f => f.endsWith('.movejs')).map(f => path.join(dir, f));
}

function main() {
  ensureDir(outRoot);

  const exampleFiles = collectFiles(examplesDir);
  const fixtureFiles = collectFiles(fixturesDir);
  
  // Check for command-line flag
  const onlyExamples = process.argv.includes('--examples-only');

  console.log('\n📦 Building Move packages from MoveJS sources...\n');
  console.log(`Examples: ${exampleFiles.length} files`);
  if (!onlyExamples) {
    console.log(`Fixtures: ${fixtureFiles.length} files`);
  } else {
    console.log(`Fixtures: SKIPPED (--examples-only mode)\n`);
  }
  console.log();
  
  // Build examples
  exampleFiles.forEach(f => buildFromFile(f, 'examples'));
  
  // Build fixtures (unless --examples-only flag)
  if (!onlyExamples) {
    fixtureFiles.forEach(f => buildFromFile(f, 'fixtures'));
  }

  console.log(`\n✅ Done. Generated packages in ${outRoot}`);
}

main();
